module.exports = {
  media: '/media',
  live: '/live',
  playlists: '/playlists',
  comments: '/comments',
  search: '/search',
  tags: '/tags',
  ads: '/ads',
  category_ads: '/category-ads',
  categories: '/categories',
  members: '/users',
  liked: '/user/action/like',
  history: '/user/action/watch',
  purchases: '/purchases',
  actions: '/actions',
  manage_media: '/manage_media',
  manage_statistics: '/manage_statistics',
  manage_users: '/manage_users',
  manage_comments: '/manage_comments',
  manage_wowza_status: '/manage_wowza/status',
  manage_wowza_applications: '/manage_wowza/applications',
};
