# Generated by GitHub Copilot on 2026-02-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.media"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("user", "media")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(default="flow", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Amount in minor units (e.g. CLP pesos)."),
                ),
                ("currency", models.CharField(default="CLP", max_length=10)),
                ("provider_token", models.CharField(blank=True, max_length=120, null=True)),
                ("provider_order_id", models.CharField(blank=True, max_length=120, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("raw_create_response", models.JSONField(blank=True, null=True)),
                ("raw_confirm_payload", models.JSONField(blank=True, null=True)),
                ("raw_status_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.media"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="downloadentitlement",
            index=models.Index(fields=["user", "media", "status"], name="payments_do_user_id_8f0c3b_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["provider", "provider_token"], name="payments_pa_provider_5e87a4_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "created_at"], name="payments_pa_status_97f792_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "media", "status"], name="payments_pa_user_id_9da52e_idx"),
        ),
    ]
