# Generated by Django 5.2.6 on 2026-06-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_customer_id', models.CharField(max_length=120, unique=True)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('pay_mode', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('credit_card_type', models.CharField(blank=True, max_length=40)),
                ('last4_card_digits', models.CharField(blank=True, max_length=8)),
                ('card_number', models.CharField(blank=True, max_length=32)),
                ('issuer_bank', models.CharField(blank=True, max_length=120)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('raw_create_response', models.JSONField(blank=True, null=True)),
                ('raw_last_register_status', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_plan_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('interval', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=3)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('trial_period_days', models.PositiveIntegerField(default=0)),
                ('days_until_due', models.PositiveIntegerField(default=3)),
                ('periods_number', models.PositiveIntegerField(default=0)),
                ('charges_retries_number', models.PositiveIntegerField(default=3)),
                ('currency_convert_option', models.PositiveSmallIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_flow_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_subscription_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending_card', 'Pending card registration'), ('active', 'Active'), ('trial', 'Trial'), ('canceled', 'Canceled'), ('inactive', 'Inactive'), ('registration_failed', 'Registration failed')], default='pending_card', max_length=30)),
                ('flow_status', models.IntegerField(blank=True, null=True)),
                ('register_token', models.CharField(blank=True, max_length=120)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('next_invoice_date', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_register_response', models.JSONField(blank=True, null=True)),
                ('raw_subscription_response', models.JSONField(blank=True, null=True)),
                ('raw_subscription_status', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='downloadentitlement',
            new_name='payments_do_user_id_2d600c_idx',
            old_name='payments_do_user_id_8f0c3b_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_provide_670d26_idx',
            old_name='payments_pa_provider_5e87a4_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_343680_idx',
            old_name='payments_pa_status_97f792_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_8faedf_idx',
            old_name='payments_pa_user_id_9da52e_idx',
        ),
        migrations.AddField(
            model_name='flowcustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['flow_plan_id', 'is_active'], name='payments_su_flow_pl_1ebbee_idx'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.flowcustomer'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='flowcustomer',
            index=models.Index(fields=['flow_customer_id', 'status'], name='payments_fl_flow_cu_af6b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'updated_at'], name='payments_us_status_9af322_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['flow_subscription_id'], name='payments_us_flow_su_a4935c_idx'),
        ),
    ]
