# Generated by Django 5.2.6 on 2026-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_flowcustomer_subscriptionplan_usersubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('pending_card', 'Registro de tarjeta pendiente'), ('active', 'Activa'), ('trial', 'En período de trial'), ('canceled', 'Cancelada'), ('inactive', 'Inactiva'), ('registration_failed', 'Registro fallido')], default='pending_card', max_length=30),
        ),
    ]
