# Generated by Django 5.2.6 on 2026-06-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_usersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='morose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
