[program:celery_short]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
process_name=%(program_name)s_%(process_num)02d
numprocs=2
user=www-data
directory=/home/mediacms.io/mediacms
priority=400
startinorder=true
command=/home/mediacms.io/bin/python3 -m celery -A cms worker --pidfile=/var/run/mediacms/%(program_name)s_%(process_num)02d.pid --loglevel=INFO --logfile=/home/mediacms.io/mediacms/logs/celery_short.log --soft-time-limit=300 -c10 -Q short_tasks -n short%(process_num)02d@%%h
