# Generated by Django 5.1.6 on 2025-04-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language__title']},
        ),
        migrations.CreateModel(
            name='AdsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ads_tag', to='files.media')),
            ],
        ),
    ]
