# Generated by Django 5.1.6 on 2025-05-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_ads_media_ad_tag_delete_adstag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
