# Generated by Django 5.1.6 on 2025-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_ads_options_alter_ads_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ads',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
