# Generated by Django 5.1.6 on 2025-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_ads_name_alter_ads_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_stream',
            field=models.BooleanField(db_index=True, default=False, help_text='If stream is activated'),
        ),
    ]
