# Generated by Django 5.1.6 on 2025-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_media_is_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_stream',
        ),
        migrations.AddField(
            model_name='media',
            name='stream',
            field=models.CharField(blank=True, db_index=True, help_text='stream path', max_length=255),
        ),
    ]
